#!/usr/bin/env python

import os
import deluge.common
import logging, sys
import distutils.util
from deluge.configmanager import ConfigManager, get_config_dir, set_config_dir

logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)

os.setgid(int(os.getenv('PGID', 0)))
os.setuid(int(os.getenv('PUID', 0)))

config_dir = '/config'
if os.path.exists(config_dir + '/core.conf.done'):
    logging.info("Initial configuration already done")
    sys.exit(0)

torrents_dir = os.getenv('TORRENTS_DIR', '/downloads')
listen_ports = map(int, os.getenv('LISTEN_PORTS', '6881,6881').split(','))
daemon_port = int(os.getenv('DAEMON_PORT', 58846))
random_port = distutils.util.strtobool(os.getenv('RANDOM_PORT', 'False'))
upnp = distutils.util.strtobool(os.getenv('UPNP', 'False'))

geoip_db_location = os.getenv('GEOIP_DB_LOCATION', config_dir + '/GeoIP/GeoIP.dat')
plugins_location = os.getenv('PLUGINS_LOCATION', config_dir + '/deluge/plugins')

move_completed_path = os.getenv('MOVE_COMPLETED_PATH', torrents_dir + '/completed')
torrentfiles_location = os.getenv('TORRENTFILES_LOCATION', torrents_dir + '/.torrents')
download_location = os.getenv('DOWNLOAD_LOCATION', torrents_dir + '/in_progress')
autoadd_location = os.getenv('AUTOADD_LOCATION', torrents_dir + '/drop')

if not os.path.exists(config_dir):
  os.makedirs(config_dir)

set_config_dir(config_dir)
config = ConfigManager(config_dir + '/core.conf')

config['move_completed_path'] = move_completed_path
config['torrentfiles_location'] = torrentfiles_location
config['download_location'] = download_location
config['autoadd_location'] = autoadd_location
config['geoip_db_location'] = geoip_db_location
config['plugins_location'] = plugins_location

config['listen_ports'] = listen_ports
config['daemon_port'] = daemon_port
config['random_port'] = random_port

try:
    config.save()
    with open(config_dir + '/core.conf.done', 'w') as f:
        f.write("done\n")
except IOError, e:
    logging.error(e)
    sys.exit(1)
