#!/usr/bin/env python

import os
import hashlib
import random
import deluge.common
import logging, sys
from deluge.config import Config

logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)

os.setgid(int(os.getenv('PGID', 0)))
os.setuid(int(os.getenv('PUID', 0)))

config_dir = '/config'
if os.path.exists(config_dir + '/web.conf.done'):
    logging.info("Initial configuration already done")
    sys.exit(0)

web_port = int(os.getenv('WEB_PORT', 8112))
password = os.getenv('DELUGE_PASSWORD', 'deluge')
daemon_port = int(os.getenv('DAEMON_PORT', 58846))

config = Config("web.conf", config_dir=config_dir)

config['default_daemon'] = '127.0.0.1:%d' % daemon_port
config['port'] = web_port

salt = hashlib.sha1(str(random.getrandbits(40))).hexdigest()
s = hashlib.sha1(salt)

config['pwd_salt'] = salt
s.update(password)
config['pwd_sha1'] = s.hexdigest()

try:
    config.save()
    with open(config_dir + "/web.conf.done", 'w') as f:
        f.write("done\n")
except IOError, e:
    print "Couldn't save new password: ", e
    sys.exit(1)
